// Data Structure
export const getHistoryChats = (fullName: string) => [
  {
    id: "11b",
    name: "11°B - Oficial",
    type: "group",
    avatar: "BookOpen",
    avatarColor: "bg-nebula-cyan/20 border-nebula-cyan/50 text-nebula-cyan",
    messages: [
      {
        id: 1,
        sender: "Profesor",
        senderColor: "text-nebula-cyan",
        content:
          "Buenos días estudiantes. Recuerden que hoy es el examen final.",
        time: "07:30 AM",
      },
      {
        id: 2,
        sender: "María",
        senderColor: "text-pink-400",
        content: "Buenos días profe, ¿a qué hora habilita el link?",
        time: "07:32 AM",
      },
      {
        id: 3,
        sender: "Profesor",
        senderColor: "text-nebula-cyan",
        content: "A las 10:45 AM en punto.",
        time: "07:35 AM",
      },
      {
        id: 4,
        sender: "Juan",
        senderColor: "text-blue-400",
        content: "Profe, ¿entra lo de la semana pasada?",
        time: "08:10 AM",
      },
      {
        id: 5,
        sender: "Profesor",
        senderColor: "text-nebula-cyan",
        content: "Sí Juan, todo lo del segundo corte.",
        time: "08:15 AM",
      },
      {
        id: 6,
        sender: "Carlos",
        senderColor: "text-green-400",
        content: "¡Qué nervios! Hice todos los talleres.",
        time: "09:00 AM",
      },
      {
        id: 7,
        sender: "Lucía",
        senderColor: "text-orange-400",
        content: "Yo también, ojalá nos vaya bien.",
        time: "09:05 AM",
      },
      {
        id: 8,
        sender: "Andrés",
        senderColor: "text-purple-400",
        content: "¿Alguien tiene el resumen del tema 3?",
        time: "09:45 AM",
      },
      {
        id: 9,
        isMe: true,
        content: "Yo lo pasé al grupo de estudio ayer.",
        time: "09:46 AM",
      },
      {
        id: 10,
        sender: "Andrés",
        senderColor: "text-purple-400",
        content: "Ah vale, ya lo busco. Gracias!",
        time: "09:47 AM",
      },
      {
        id: 11,
        sender: "Profesor",
        senderColor: "text-nebula-cyan",
        content: "Atención. Aquí tienen el link del examen:",
        time: "10:45 AM",
      },
      {
        id: 12,
        sender: "Profesor",
        senderColor: "text-nebula-cyan",
        content: `¡Hola ${fullName || "Estudiante"}! Por favor, ingresa a este enlace para realizar tu examen de inglés:`,
        link: true,
        time: "10:45 AM",
      },
      {
        id: 13,
        sender: "María",
        senderColor: "text-pink-400",
        content: "Listo profe.",
        time: "10:46 AM",
      },
      {
        id: 14,
        sender: "Juan",
        senderColor: "text-blue-400",
        content: "Listo profe, ya entré.",
        time: "10:46 AM",
      },
      { id: 15, isMe: true, content: "Listo profe.", time: "10:46 AM" },
      {
        id: 16,
        sender: "Carlos",
        senderColor: "text-green-400",
        content: "Listo profe.",
        time: "10:47 AM",
      },
      {
        id: 17,
        sender: "Lucía",
        senderColor: "text-orange-400",
        content: "Listo profe.",
        time: "10:47 AM",
      },
      {
        id: 18,
        sender: "Esteban",
        senderColor: "text-yellow-400",
        content: "Profe no me abre el link :(",
        time: "10:48 AM",
      },
      {
        id: 19,
        sender: "Profesor",
        senderColor: "text-nebula-cyan",
        content: "Esteban, intenta recargar la página o usa el navegador niX.",
        time: "10:49 AM",
      },
      {
        id: 20,
        sender: "Esteban",
        senderColor: "text-yellow-400",
        content: "Ya funcionó, gracias!",
        time: "10:50 AM",
      },
      {
        id: 21,
        sender: "Valentina",
        senderColor: "text-red-400",
        content: "Listo profe.",
        time: "10:50 AM",
      },
      {
        id: 22,
        sender: "Mateo",
        senderColor: "text-indigo-400",
        content: "Listo profe.",
        time: "10:51 AM",
      },
      {
        id: 23,
        sender: "Sofía",
        senderColor: "text-teal-400",
        content: "Listo profe.",
        time: "10:52 AM",
      },
      {
        id: 24,
        sender: "Diego",
        senderColor: "text-emerald-400",
        content: "Listo profe.",
        time: "10:52 AM",
      },
      {
        id: 25,
        sender: "Camila",
        senderColor: "text-amber-400",
        content: "Listo profe.",
        time: "10:53 AM",
      },
      {
        id: 26,
        sender: "Jorge",
        senderColor: "text-cyan-400",
        content: "Listo profe.",
        time: "10:54 AM",
      },
      {
        id: 27,
        sender: "Elena",
        senderColor: "text-lime-400",
        content: "Listo profe.",
        time: "10:55 AM",
      },
      {
        id: 28,
        sender: "Felipe",
        senderColor: "text-rose-400",
        content: "Listo profe.",
        time: "10:55 AM",
      },
      {
        id: 29,
        sender: "Gabriela",
        senderColor: "text-sky-400",
        content: "Listo profe.",
        time: "10:56 AM",
      },
      {
        id: 30,
        sender: "Samuel",
        senderColor: "text-violet-400",
        content: "Listo profe.",
        time: "10:57 AM",
      },
    ],
  },
  {
    id: "real",
    name: "Los del Real ⚽",
    type: "group",
    avatar: "Users",
    avatarColor: "bg-green-500/20 border-green-500/50 text-green-500",
    messages: [
      {
        id: 1,
        sender: "Carlos",
        senderColor: "text-green-400",
        content: "¿A qué hora es el partido hoy?",
        time: "09:30 AM",
      },
      {
        id: 2,
        sender: "Luis",
        senderColor: "text-blue-400",
        content: "A las 8, llevo el balón.",
        time: "09:32 AM",
      },
      {
        id: 3,
        isMe: true,
        content: "Yo llego un poco tarde, como a las 8:15.",
        time: "09:35 AM",
      },
      {
        id: 4,
        sender: "Mateo",
        senderColor: "text-red-400",
        content: "Dale no pasa nada.",
        time: "09:36 AM",
      },
      {
        id: 5,
        sender: "Carlos",
        senderColor: "text-green-400",
        content: "¿Quién más falta por confirmar?",
        time: "09:40 AM",
      },
      {
        id: 6,
        sender: "Andrés",
        senderColor: "text-purple-400",
        content: "Yo voy!",
        time: "09:42 AM",
      },
      {
        id: 7,
        sender: "Juan",
        senderColor: "text-orange-400",
        content: "Yo también.",
        time: "10:00 AM",
      },
      {
        id: 8,
        sender: "Luis",
        senderColor: "text-blue-400",
        content: "Somos 10 entonces, partido completo.",
        time: "10:05 AM",
      },
      {
        id: 9,
        sender: "Diego",
        senderColor: "text-indigo-400",
        content: "Ojo con el clima, parece que va a llover.",
        time: "10:15 AM",
      },
      {
        id: 10,
        isMe: true,
        content: "Si llueve jugamos en la sintética techada.",
        time: "10:20 AM",
      },
      {
        id: 11,
        sender: "Carlos",
        senderColor: "text-green-400",
        content: "Buena idea.",
        time: "10:22 AM",
      },
      {
        id: 12,
        sender: "Valentina",
        senderColor: "text-pink-400",
        content: "Yo voy a ver el partido!",
        time: "10:30 AM",
      },
      {
        id: 13,
        sender: "Luis",
        senderColor: "text-blue-400",
        content: "Lleva agua jaja.",
        time: "10:32 AM",
      },
      {
        id: 14,
        sender: "Mateo",
        senderColor: "text-red-400",
        content: "Y la cámara para las fotos del equipo.",
        time: "10:35 AM",
      },
      { id: 15, isMe: true, content: "Yo llevo el trípode.", time: "10:38 AM" },
      {
        id: 16,
        sender: "Santi",
        senderColor: "text-emerald-400",
        content: "¿Jugamos contra los de 11A?",
        time: "11:00 AM",
      },
      {
        id: 17,
        sender: "Carlos",
        senderColor: "text-green-400",
        content: "Si, ya aceptaron el reto.",
        time: "11:02 AM",
      },
      {
        id: 18,
        sender: "Luis",
        senderColor: "text-blue-400",
        content: "Les vamos a ganar fácil.",
        time: "11:05 AM",
      },
      {
        id: 19,
        sender: "Andrés",
        senderColor: "text-purple-400",
        content: "No te confíes, tienen un delantero bueno.",
        time: "11:10 AM",
      },
      {
        id: 20,
        sender: "Juan",
        senderColor: "text-orange-400",
        content: "Nosotros tenemos a la mejor defensa.",
        time: "11:15 AM",
      },
      {
        id: 21,
        isMe: true,
        content: "Total confianza en el equipo.",
        time: "11:20 AM",
      },
      {
        id: 22,
        sender: "Diego",
        senderColor: "text-indigo-400",
        content: "¿Llevamos las camisetas blancas?",
        time: "11:25 AM",
      },
      {
        id: 23,
        sender: "Carlos",
        senderColor: "text-green-400",
        content: "Sí, todos de blanco.",
        time: "11:28 AM",
      },
      {
        id: 24,
        sender: "Mateo",
        senderColor: "text-red-400",
        content: "Confirmado.",
        time: "11:30 AM",
      },
      {
        id: 25,
        sender: "Luis",
        senderColor: "text-blue-400",
        content: "Cero excusas hoy.",
        time: "11:35 AM",
      },
      {
        id: 26,
        sender: "Andrés",
        senderColor: "text-purple-400",
        content: "A darlo todo.",
        time: "11:40 AM",
      },
      {
        id: 27,
        sender: "Santi",
        senderColor: "text-emerald-400",
        content: "¡Vamos Real!",
        time: "11:45 AM",
      },
      { id: 28, isMe: true, content: "¡A ganar!", time: "11:50 AM" },
      {
        id: 29,
        sender: "Jorge",
        senderColor: "text-cyan-400",
        content: "Lleven protector solar por si acaso.",
        time: "11:55 AM",
      },
      {
        id: 30,
        sender: "Luis",
        senderColor: "text-blue-400",
        content: "A las 8 ya no hay sol Jorge...",
        time: "11:58 AM",
      },
    ],
  },
  {
    id: "kode",
    name: "The Kode Team 💻",
    type: "group",
    avatar: "Terminal",
    avatarColor:
      "bg-nebula-primary/20 border-nebula-primary/50 text-nebula-primary",
    messages: [
      {
        id: 1,
        sender: "David",
        senderColor: "text-nebula-primary",
        content: "El deploy falló otra vez en producción 💀",
        time: "11:15 AM",
      },
      {
        id: 2,
        sender: "Ana",
        senderColor: "text-orange-400",
        content:
          "Revisa los logs de Docker, seguro es una variable de entorno.",
        time: "11:17 AM",
      },
      {
        id: 3,
        isMe: true,
        content:
          "Estoy revisando el Sentry, parece un error de conexión a la BD.",
        time: "11:20 AM",
      },
      {
        id: 4,
        sender: "David",
        senderColor: "text-nebula-primary",
        content: "¿La BD de staging o prod?",
        time: "11:22 AM",
      },
      {
        id: 5,
        isMe: true,
        content: "Prod. El pool de conexiones está lleno.",
        time: "11:25 AM",
      },
      {
        id: 6,
        sender: "Ana",
        senderColor: "text-orange-400",
        content: "Hay que aumentar el max_connections o revisar si hay fugas.",
        time: "11:27 AM",
      },
      {
        id: 7,
        sender: "Kevin",
        senderColor: "text-green-400",
        content: "Encontré un bucle infinito en el servicio de reportes.",
        time: "11:30 AM",
      },
      {
        id: 8,
        sender: "David",
        senderColor: "text-nebula-primary",
        content: "¡Ese debe ser! Bloquea todas las conexiones.",
        time: "11:32 AM",
      },
      {
        id: 9,
        isMe: true,
        content: "Kevin, ¿puedes hacer un hotfix rápido?",
        time: "11:35 AM",
      },
      {
        id: 10,
        sender: "Kevin",
        senderColor: "text-green-400",
        content: "En eso estoy, subiendo rama...",
        time: "11:38 AM",
      },
      {
        id: 11,
        sender: "Ana",
        senderColor: "text-orange-400",
        content: "Avisen cuando esté el PR para revisarlo.",
        time: "11:40 AM",
      },
      {
        id: 12,
        sender: "David",
        senderColor: "text-nebula-primary",
        content: "Yo le doy el approve de una.",
        time: "11:42 AM",
      },
      { id: 13, isMe: true, content: "Listo, PR abierto.", time: "11:45 AM" },
      {
        id: 14,
        sender: "Kevin",
        senderColor: "text-green-400",
        content: "Test unitarios pasados.",
        time: "11:47 AM",
      },
      {
        id: 15,
        sender: "Ana",
        senderColor: "text-orange-400",
        content: "Mergeado a main.",
        time: "11:50 AM",
      },
      {
        id: 16,
        sender: "David",
        senderColor: "text-nebula-primary",
        content: "Desplegando de nuevo...",
        time: "11:52 AM",
      },
      {
        id: 17,
        sender: "David",
        senderColor: "text-nebula-primary",
        content: "¡Funciona! El sitio volvió a la vida.",
        time: "11:55 AM",
      },
      {
        id: 18,
        isMe: true,
        content: "Menos mal. Qué susto.",
        time: "11:57 AM",
      },
      {
        id: 19,
        sender: "Ana",
        senderColor: "text-orange-400",
        content: "Hay que programar un post-mortem.",
        time: "12:00 PM",
      },
      {
        id: 20,
        sender: "Kevin",
        senderColor: "text-green-400",
        content: "Sí, para que no vuelva a pasar.",
        time: "12:02 PM",
      },
      {
        id: 21,
        sender: "David",
        senderColor: "text-nebula-primary",
        content: "Agreguen tests de integración para ese caso.",
        time: "12:05 PM",
      },
      {
        id: 22,
        isMe: true,
        content: "Yo me encargo de la documentación del bug.",
        time: "12:08 PM",
      },
      {
        id: 23,
        sender: "Ana",
        senderColor: "text-orange-400",
        content: "Gracias equipo. Buen trabajo bajo presión.",
        time: "12:10 PM",
      },
      {
        id: 24,
        sender: "David",
        senderColor: "text-nebula-primary",
        content: "¿Sale un café virtual para celebrar?",
        time: "12:12 PM",
      },
      {
        id: 25,
        sender: "Kevin",
        senderColor: "text-green-400",
        content: "De una.",
        time: "12:15 PM",
      },
      { id: 26, isMe: true, content: "Acepto.", time: "12:17 PM" },
      {
        id: 27,
        sender: "Ana",
        senderColor: "text-orange-400",
        content: "Cierren los tickets de Jira antes jaja.",
        time: "12:20 PM",
      },
      {
        id: 28,
        sender: "David",
        senderColor: "text-nebula-primary",
        content: "Uf, cierto.",
        time: "12:22 PM",
      },
      {
        id: 29,
        isMe: true,
        content: "Listo, tickets cerrados.",
        time: "12:25 PM",
      },
      {
        id: 30,
        sender: "Kevin",
        senderColor: "text-green-400",
        content: "Ahora sí, café!",
        time: "12:28 PM",
      },
    ],
  },
  {
    id: "parche",
    name: "El Parche 🍕",
    type: "group",
    avatar: "Coffee",
    avatarColor: "bg-orange-500/20 border-orange-500/50 text-orange-500",
    messages: [
      {
        id: 1,
        sender: "Sebas",
        senderColor: "text-yellow-400",
        content: "¿Sale pizza hoy o qué?",
        time: "12:00 PM",
      },
      {
        id: 2,
        sender: "Marta",
        senderColor: "text-pink-400",
        content: "De una, yo pongo la casa.",
        time: "12:05 PM",
      },
      {
        id: 3,
        isMe: true,
        content: "Yo llevo las gaseosas.",
        time: "12:10 PM",
      },
      {
        id: 4,
        sender: "Sebas",
        senderColor: "text-yellow-400",
        content: "¿A qué hora nos vemos?",
        time: "12:15 PM",
      },
      {
        id: 5,
        sender: "Marta",
        senderColor: "text-pink-400",
        content: "A las 7 está bien.",
        time: "12:20 PM",
      },
      {
        id: 6,
        sender: "Felipe",
        senderColor: "text-blue-400",
        content: "Yo llevo un juego de mesa.",
        time: "12:25 PM",
      },
      { id: 7, isMe: true, content: "¿Catan?", time: "12:30 PM" },
      {
        id: 8,
        sender: "Felipe",
        senderColor: "text-blue-400",
        content: "Obvio.",
        time: "12:32 PM",
      },
      {
        id: 9,
        sender: "Sebas",
        senderColor: "text-yellow-400",
        content: "¿Qué pizzas pedimos?",
        time: "12:40 PM",
      },
      {
        id: 10,
        sender: "Marta",
        senderColor: "text-pink-400",
        content: "Una de pepperoni y otra hawaiana.",
        time: "12:45 PM",
      },
      {
        id: 11,
        sender: "Felipe",
        senderColor: "text-blue-400",
        content: "Hawaiana noooooo.",
        time: "12:47 PM",
      },
      {
        id: 12,
        isMe: true,
        content: "Jaja la eterna pelea.",
        time: "12:50 PM",
      },
      {
        id: 13,
        sender: "Sebas",
        senderColor: "text-yellow-400",
        content: "Pidamos una de carnes entonces.",
        time: "12:55 PM",
      },
      {
        id: 14,
        sender: "Marta",
        senderColor: "text-pink-400",
        content: "Bueno vale.",
        time: "01:00 PM",
      },
      {
        id: 15,
        sender: "Felipe",
        senderColor: "text-blue-400",
        content: "Gracias.",
        time: "01:02 PM",
      },
      {
        id: 16,
        isMe: true,
        content: "¿Llevo helado también?",
        time: "01:10 PM",
      },
      {
        id: 17,
        sender: "Sebas",
        senderColor: "text-yellow-400",
        content: "Uf sí por fa.",
        time: "01:15 PM",
      },
      {
        id: 18,
        sender: "Marta",
        senderColor: "text-pink-400",
        content: "¿De qué sabor?",
        time: "01:20 PM",
      },
      {
        id: 19,
        isMe: true,
        content: "Vainilla y chocolate para no fallar.",
        time: "01:25 PM",
      },
      {
        id: 20,
        sender: "Felipe",
        senderColor: "text-blue-400",
        content: "Perfecto.",
        time: "01:30 PM",
      },
      {
        id: 21,
        sender: "Sebas",
        senderColor: "text-yellow-400",
        content: "Yo paso por Felipe a las 6:45.",
        time: "02:00 PM",
      },
      {
        id: 22,
        sender: "Felipe",
        senderColor: "text-blue-400",
        content: "Dale, aquí te espero.",
        time: "02:05 PM",
      },
      {
        id: 23,
        isMe: true,
        content: "Yo llego directo en el carro.",
        time: "02:10 PM",
      },
      {
        id: 24,
        sender: "Marta",
        senderColor: "text-pink-400",
        content: "Vale, les mando la ubicación por si las dudas.",
        time: "02:15 PM",
      },
      {
        id: 25,
        sender: "Marta",
        senderColor: "text-pink-400",
        content: "📍 Ubicación enviada.",
        time: "02:16 PM",
      },
      { id: 26, isMe: true, content: "Recibido.", time: "02:20 PM" },
      {
        id: 27,
        sender: "Sebas",
        senderColor: "text-yellow-400",
        content: "¿Llevo parlante?",
        time: "02:30 PM",
      },
      {
        id: 28,
        sender: "Marta",
        senderColor: "text-pink-400",
        content: "Yo tengo uno aquí.",
        time: "02:35 PM",
      },
      {
        id: 29,
        isMe: true,
        content: "Mejor, así no cargas nada.",
        time: "02:40 PM",
      },
      {
        id: 30,
        sender: "Felipe",
        senderColor: "text-blue-400",
        content: "¡Nos vemos en un rato!",
        time: "03:00 PM",
      },
    ],
  },
  {
    id: "mama",
    name: "Mamá ❤️",
    type: "private",
    avatar: "Heart",
    avatarColor: "bg-red-500/20 border-red-500/50 text-red-500",
    messages: [
      {
        id: 1,
        sender: "Mamá",
        content: "Hola hijo, ¿cómo vas?",
        time: "08:00 AM",
      },
      {
        id: 2,
        isMe: true,
        content: "Hola ma, bien. Estudiando para el examen.",
        time: "08:05 AM",
      },
      {
        id: 3,
        sender: "Mamá",
        content: "Qué bueno. ¿Desayunaste bien?",
        time: "08:10 AM",
      },
      {
        id: 4,
        isMe: true,
        content: "Sí, unos huevos y café.",
        time: "08:15 AM",
      },
      {
        id: 5,
        sender: "Mamá",
        content: "Me alegra. Mucha suerte hoy.",
        time: "08:20 AM",
      },
      {
        id: 6,
        isMe: true,
        content: "Gracias ma, la necesito jaja.",
        time: "08:25 AM",
      },
      {
        id: 7,
        sender: "Mamá",
        content: "Tú eres muy inteligente, te irá bien.",
        time: "08:30 AM",
      },
      {
        id: 8,
        isMe: true,
        content: "Te aviso cuando termine.",
        time: "10:00 AM",
      },
      {
        id: 9,
        sender: "Mamá",
        content: "¿Ya terminaste el examen?",
        time: "10:50 AM",
      },
      {
        id: 10,
        isMe: true,
        content: "Aún no ma, estoy en ello.",
        time: "10:55 AM",
      },
    ],
  },
  {
    id: "hermana",
    name: "Hermana 🤜🤛",
    type: "private",
    avatar: "User",
    avatarColor: "bg-purple-500/20 border-purple-500/50 text-purple-500",
    messages: [
      {
        id: 1,
        sender: "Hermana",
        content: "¿Viste mi cargador?",
        time: "09:00 AM",
      },
      {
        id: 2,
        isMe: true,
        content: "No, búscalo en la sala.",
        time: "09:05 AM",
      },
      { id: 3, sender: "Hermana", content: "No está.", time: "09:10 AM" },
      { id: 4, isMe: true, content: "Entonces no sé.", time: "09:15 AM" },
      {
        id: 5,
        sender: "Hermana",
        content: "Lo tenías tú ayer.",
        time: "09:20 AM",
      },
      {
        id: 6,
        isMe: true,
        content: "Ah verdad, está en mi mochila.",
        time: "09:25 AM",
      },
      { id: 7, sender: "Hermana", content: "Tráelo 😒", time: "09:30 AM" },
      { id: 8, isMe: true, content: "Cuando vuelva a casa.", time: "10:00 AM" },
      {
        id: 9,
        sender: "Hermana",
        content: "Me traes algo de comer",
        time: "11:00 AM",
      },
      { id: 10, isMe: true, content: "Si me queda plata.", time: "11:05 AM" },
    ],
  },
  {
    id: "andres",
    name: "Andrés",
    type: "private",
    avatar: "User",
    avatarColor: "bg-blue-500/20 border-blue-500/50 text-blue-500",
    messages: [
      {
        id: 1,
        sender: "Andrés",
        content: "¿Estudiaste para el examen?",
        time: "08:30 AM",
      },
      { id: 2, isMe: true, content: "Un poco, ¿tú?", time: "08:35 AM" },
      {
        id: 3,
        sender: "Andrés",
        content: "Nada, me quedé viendo series.",
        time: "08:40 AM",
      },
      {
        id: 4,
        isMe: true,
        content: "Qué irresponsable jaja.",
        time: "08:45 AM",
      },
      {
        id: 5,
        sender: "Andrés",
        content: "Ayúdame con las difíciles.",
        time: "08:50 AM",
      },
      { id: 6, isMe: true, content: "Veremos.", time: "08:55 AM" },
      {
        id: 7,
        sender: "Andrés",
        content: "¿Sabes qué entra?",
        time: "09:00 AM",
      },
      {
        id: 8,
        isMe: true,
        content: "Lo que dijo el profe en el grupo.",
        time: "09:05 AM",
      },
      {
        id: 9,
        sender: "Andrés",
        content: "Pasa la 3 del examen jaja",
        time: "10:48 AM",
      },
      { id: 10, isMe: true, content: "Concentrate wey.", time: "10:50 AM" },
    ],
  },
];
